lidar cc lidar.c mirror.o delay.o lidar.h -o lidar
#alidar 

testMirror cc testMirror.c mirror.o lidar.h -o testMirror


delay.o cc -c delay.c lidar.h delay.h -o delay.o
mirror.o cc -c mirror.c lidar.h mirror.h -o mirror.o

clean rm *.o
